--- Crear tabla de publicaciones

CREATE TABLE Publicaciones
("AUTHOR ID" VARCHAR(50) NOT NULL
	, "LAST NAME" VARCHAR(50) NOT NULL
	, "FIRST NAME" VARCHAR(50) NOT NULL
	, TITLE VARCHAR(50) NOT NULL
	, PUBLISHER VARCHAR(50) NOT NULL);
	


