-- Challenge 1 - Who Have Published What At Where? --
SHOW TABLES;
SHOW COLUMNS FROM AUTHORS; 
SHOW COLUMNS FROM TITLES;
SHOW COLUMNS FROM PUBLISHERS;
SHOW COLUMNS FROM TITLEAUTHOR;
SHOW COLUMNS FROM PUB_INFO;

SELECT 
    AUTHORS.AU_ID AS AUTHOR_ID,
    AUTHORS.AU_LNAME AS LAST_NAME,
    AUTHORS.AU_FNAME AS FIRST_NAME,
    TITLES.TITLE,
    PUBLISHERS.PUB_NAME AS PUBLISHER
FROM 
    AUTHORS
JOIN 
    TITLEAUTHOR ON AUTHORS.AU_ID = TITLEAUTHOR.AU_ID
JOIN 
    TITLES ON TITLEAUTHOR.TITLE_ID = TITLES.TITLE_ID
JOIN 
    PUBLISHERS ON TITLES.PUB_ID = PUBLISHERS.PUB_ID;

-- Challenge 2 - Who Have Published How Many At Where? --

SELECT 
    AUTHORS.AU_ID AS AUTHOR_ID,
    AUTHORS.AU_LNAME AS LAST_NAME,
    AUTHORS.AU_FNAME AS FIRST_NAME,
    PUBLISHERS.PUB_NAME AS PUBLISHER,
    COUNT(TITLES.TITLE_ID) AS TitleCount
FROM 
    AUTHORS
JOIN 
    TITLEAUTHOR ON AUTHORS.AU_ID = TITLEAUTHOR.AU_ID
JOIN 
    TITLES ON TITLEAUTHOR.TITLE_ID = TITLES.TITLE_ID
JOIN 
    PUBLISHERS ON TITLES.PUB_ID = PUBLISHERS.PUB_ID
GROUP BY 
    AUTHORS.AU_ID, AUTHORS.AU_LNAME, AUTHORS.AU_FNAME, PUBLISHERS.PUB_NAME;

-- Challenge 3 - Best Selling Authors --

SELECT 
    AUTHORS.AU_ID AS AUTHOR_ID,
    AUTHORS.AU_LNAME AS LAST_NAME,
    AUTHORS.AU_FNAME AS FIRST_NAME,
    SUM(SALES.QTY) AS TOTAL
    
FROM 
    AUTHORS
JOIN 
    TITLEAUTHOR ON AUTHORS.AU_ID = TITLEAUTHOR.AU_ID
JOIN 
    TITLES ON TITLEAUTHOR.TITLE_ID = TITLES.TITLE_ID
JOIN 
    SALES ON TITLES.TITLE_ID = SALES.TITLE_ID
GROUP BY 
    AUTHORS.AU_ID, AUTHORS.AU_LNAME, AUTHORS.AU_FNAME

order by `TOTAL` desc limit 3;
    
-- Challenge 4 - Best Selling Authors Ranking --

SELECT 
    AUTHORS.AU_ID AS AUTHOR_ID,
    AUTHORS.AU_LNAME AS LAST_NAME,
    AUTHORS.AU_FNAME AS FIRST_NAME,
    SUM(SALES.QTY) AS TOTAL
    
FROM 
    AUTHORS
JOIN 
    TITLEAUTHOR ON AUTHORS.AU_ID = TITLEAUTHOR.AU_ID
JOIN 
    TITLES ON TITLEAUTHOR.TITLE_ID = TITLES.TITLE_ID
JOIN 
    SALES ON TITLES.TITLE_ID = SALES.TITLE_ID
GROUP BY 
    AUTHORS.AU_ID, AUTHORS.AU_LNAME, AUTHORS.AU_FNAME
ORDER BY `TOTAL` desc limit 23